### ISSUE TITLE
Modify search logic for get_obt_data, get_pending_fio_requests, get_sent_fio_requests

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fio#102]
This story implements FIP-1 functionality:

https://github.com/fioprotocol/fips/blob/master/fip-1.md

and covers:
- Updating get_obt_data, get_pending_fio_requests, and get_sent_fio_requests as described here: https://github.com/fioprotocol/fips/blob/master/fip-1.md#modification-to-existing-queries

**Comment by dapixcasey** [comment]
PRs have been submitted and testing has begun.

**Comment by dapixcasey** [comment]
A new table structure was proposed inside the fio.request.obt contract:

    struct ledgerItems {
         vector<uint64_t> fio_request_ids;
         vector<uint64_t> recordobt_ids;
    }

Index Table:

    struct [[eosio::action]] reqledger {
          uint64_t account;
          ledgerItems transactions;

          uint64_t primary_key() const { return account; }
     }

**Example:**   
 **Account:** d98asauia
 **Transactions:**     
- fio_request_ids[6,7,1, 55]
- recordobt_ids[13,2,544,23232] 

The above solution still does not fix the problem of iterating through the status table linearly. Example: A user requesting pending data needs to check a status record for each entry to see if it is still in the pending stage of the FIO workflow. This causes problems when the user has multiple transactions that have been completed before and after the record requested. To achieve an accurate more and offset value, you would have to search every record O((n+1)!). This type of structure does not support the type of FIO transactional record retrieval required. To achieve this the following proposal aims at fixing the overall architect and design of how requests and obt actions are stored on the blockchain. 

Removal of old status & recordobt_info tables and combine them into a single table will be the best approach going forward:

**Removed Table Structure:**

    struct [[eosio::action]] fioreqstss {
       uint64_t id;
       uint64_t fio_request_id;
       uint64_t status; //oversized variable for an enum
       string metadata;   //this contains a json string with metadata regarding the response to a request only.

       uint64_t time_stamp; // not used or returned on any API endpoint
    };

Every request has one of these entries inside a table. This will begin to become a tedious task of interaction as the chain grows. 

Add the following to the new fiotxts table:
- uint64_t id;
- string metadata;  
- uint64_t update_time;
- uint64_t fio_data_type;

We would be renaming the following data memebers:
- **time_stamp** to **init_time**. 
-- The clear distinction between both timestamps allows for easier development. 

We would still be using the following enum to classify statuses however a new status code has been added for obt and other types of blockchain actions:

    enum class trxstatus {
       requested = 0,
       rejected = 1,
       sent_to_blockchain = 2,
       cancelled = 3,
       obt_action = 4,
       other = 5
    };

**id** will be the new primary key for ALL transactions while still storing **fio_request_id**. This will allow for optimized searching and allow for a clear distinction between obt records. This will also ease development since the ordering of obt and request data migrations won't be required to be linearly transferred. New **fio_request_ids** will still be based on **available_primary_key** and will match all new records that are sent on the FIO blockchain. 

 
#########################################
New request table: 

    struct [[eosio::action]] fiotxt {
       uint 64_t id;         // main lookup key
       uint64_t fio_request_id = 0;        // Keeping this in to look up past requests.
       uint128_t payer_fio_addr_hex;       // 'Allows for future searches on payer fio address. Needed?
       uint128_t payee_fio_addr_hex;     // 'Allows for future searches on payee fio address. Needed?
       uint8_t fio_data_type;  //Request (0) , OBT (4) , Pub address request (5) referenced from trxstatus enum
       uint64_t init_time;       // 'Rename of time_stamp
       string payer_fio_addr;    // 'Needed for return info
       string payee_fio_addr;     // 'Needed for return info
       string payer_key = nullptr;     // 'Needed for return info
       string payee_key = nullptr;     // 'Needed for return info
       uint128_t payer_key_hex;     // 'Allows for future searches on payee fio pub key. Needed?
       uint128_t payee_key_hex;

       string content;    // 'Holds metadata
       uint64_t update_time; // This will be set to the same time as init_time to allow for simple conditional checks if an update has been made to the transaction.

       //Future use
       string futureuse_string1 = nullptr;
       string futureuse_string2 = nullptr;
       uint64_t futureuse_uint64 = 0;
       uint128_t futureuse_uint128 = 0;
    };

Update to the proposed ledger structure used in the transactions vector ( shown above in V1 ).

    struct ledgerItems {

       std::vector<uint64_t> pending_action_ids;    // 'These are the incoming Pending Requests. Do we need a “rejected” status here, or just delete? If requestee sends funds, delete from pending and add to obt_actions_id.
       std::vector<uint64_t> sent_action_ids;    // 'These are the Sent Requests: requestor: [44]
       std::vector<uint64_t> cancelled_action_ids;    // 'Why are we keeping around cancelled requests? Do we need a separate API call? 
       std::vector<uint64_t> obt_action_ids;      // 'All direct sends, and sends in response to a request. [44,78]
    };

**Use cases:**
FIO Request:
- Record is created and index is stored inside sent_actions_ids of the payee and pending_action_ids for the payer. 

Record is: 
- approved - status is updated and index is removed from payers pending_action_ids and placed inside the obt_action_ids for both payee and payer. ( double entry for payee )
- canceled - status is updated and index is removed from payers pending_action_ids but only the payee has the index stored inside cancelled_action_ids ( double entry for payee )
- rejected - status is updated and index is removed from payers pending_action_ids. This record will no longer be on the payers transactional history when calling an API endpoint

Pros:

- Obt records regardless of payee or payer are stored in order based on time. 
- Fast and efficient record retrieval.
- **offset** and **more** are easily calculated based on single table queries.
- Request obt request ids are easily comparable. ( if id != 0 && fio_request_id == 0 )
- Remove the need for 3 tables!

Cons:

- Require updates to all actions inside the fio.request contract that modify status.
- Double integer entry for each record.
- Add migration of another table to migration process.

**Comment by ericbutz** [comment]
This feature was delivered. Closing.

Release information

Transfer FIO Domain released in [fio v2.0.0](https://github.com/fioprotocol/fio/releases/tag/v2.0.0), [fio.contracts v2.1.0](https://github.com/fioprotocol/fio.contracts/releases/tag/v2.1.0)

Transfer FIO Address released in [fio v3.0.0](https://github.com/fioprotocol/fio/releases/tag/v3.0.0), [fio.contracts v2.3.0](https://github.com/fioprotocol/fio.contracts/releases/tag/v2.3.0). For v2.3.0 it is only possible to transfer a FIO Address that has no associated FIO Request or OBT Record data. The ability to transfer any FIO Address will be released in a future contract release.
