### ISSUE TITLE
FIO V1 History: Duplicate trnsfiopubky transactions

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fio#106]
Multiple transfer fio pub key transactions are showing up in the Explorer. For example see:
https://explorer.fioprotocol.io/account/o3vozszmxmto

**Comment by adsorptionenthalpy** [comment]
From @lukestokes 
![image](https://user-images.githubusercontent.com/37982984/81109692-b68c9200-8ed7-11ea-9ece-9b45c335a8a9.png)


Raw data doesn't show up: https://explorer.fioprotocol.io/transaction/28cf9d4afa8272decc4197bdec4408ac81c73cf619caeed694a97a331911f190

**Comment by adsorptionenthalpy** [comment]
Transactions seem to be accounted for in the latest history plugin fix. Should be making it into the next release.

For trnsfiopbkey, the following history insertions take place:

action trace inserted by account receiver - entry for the contract account
action trace inserted by actor - filtered and inserted if the param exists, action trace is inserted for the actor account
action trace inserted by hashed down fio pub key - in this case, the receiver may not exist yet as it was just created before the transfer occurred, additional insertion was created using an account that was derived from the payee public key

The caching of the three separate entries of the same action allows transaction to be searchable by sender, receiver or payee account. So, what we get is all 3 of those action traces when looking up by account.
There is a unique action_digest that we will attempt to leverage to filter out the duplicate results. Discussing the next steps with the team...

**Comment by adsorptionenthalpy** [comment]
Adam A - Dapix, [01.05.20 12:35]
Hey @any_x . Seeing some duplication for a some transactions, specifically trnsfiopbky. This is the current modified history plugin. Trying to rule out the plugin itself, could the the explorer..
https://github.com/fioprotocol/fio/blob/feature/MAS-1563_temp/plugins/history_plugin/history_plugin.cpp#L188-L264

![image](https://user-images.githubusercontent.com/37982984/81109795-e340a980-8ed7-11ea-9c47-dda19bd43e03.png)

Aaron Cox (jesta) — Greymass, [01.05.20 13:01]
I believe that's the default behavior, it's returning all traces involving the account being queried. Sadly it doesn't also filter the traces to the account being notified.

Aaron Cox (jesta) — Greymass, [01.05.20 13:03]
It can be filtered at the explorer level by receiver though I believe. Those 3 traces being returned have unique receiver fields of:

- fio.token (the contract)
- gjkdwmtx2tse (the originating account)
- l35p5swqgvoo (the destination account)

Adam A - Dapix, [01.05.20 13:12]
Makes sense. Filtering out duplicate transactions for the receiver at the explorer should be easy... thanks

Aaron Cox (jesta) — Greymass, [01.05.20 13:15]
No problem!

Aaron Cox (jesta) — Greymass, [01.05.20 13:16]
Our history viewer in the wallet also suffered from those duplicates, though we never fixed it. I don't remember if there was some reason we didn't do it though, this was a long time ago we looked into it.

Aaron Cox (jesta) — Greymass, [01.05.20 13:17]
It's possible that the receiver was incorrect on some of the transactions we acutally wanted to displayed.

Aaron Cox (jesta) — Greymass, [01.05.20 13:17]
Just saying all this so you're aware and can make sure going this route doesn't eliminate some sort of data you actually want 😉

Adam A - Dapix, [01.05.20 13:47]
Already had a situation where we were storing incorrect account names for address and domain registration actions that weren’t supplied with an owner fio public key.  Oops. 
That’s been cleaned up. 1 duplicate makes sense when you account for both sender and receiver, but 2 duplicates, that’s a little confusing

Adam A - Dapix, [05.05.20 10:36]
Hypothetical question related to the latest changes of the history plugin, just throwing it out here. 
We introduced duplicate results by account_name when doing additional insertions of action traces (which are working great)... if get_actions endpoint were modified to filter out results with identical action digests, what would this harm ?

Adam A - Dapix, [05.05.20 10:43]
The actions are exactly the same. If we leave out the extra ones from the result, I only see positives at this point so correct me if wrong.

Adam A - Dapix, [05.05.20 10:47]
We could very easily do the filtering on the block explorer or any FR, but dapix product team has concluded I should pursue a clean and compatible solution at the api since we are seeing some noticeable differences in how some of the wallets handle action history.

Adam A - Dapix, [05.05.20 10:48]
@jestagram

Aaron Cox (jesta) — Greymass, [05.05.20 12:52]
I personally don't know of any issues it'd cause, so long as some transactions don't go missing. 

Are we talking about filtering at the API call level or in the actual index/storage level? 

@any_x might have a better idea than I do if this would cause any headaches.

Luke Stokes, [05.05.20 13:41]
We talked a little yesterday and today about this and I'm wondering if it makes sense to have a call with yourselves, Igor (for Hyperion), what's his name from Amseterdam and his history solution, etc... make sure we are all on the same page as to what should go into the block_log and how that should be indexed for a history solution and how those things should be filtered when showing explorer history.

Luke Stokes, [05.05.20 13:42]
the Bloks guys are going to start to working on an integration. We currently have different wallet experiences, from what I hear, regarding edge and trust. I think Edge uses Hyperion, but I'm not sure.

Luke Stokes, [05.05.20 13:42]
Should we start this conversation in the EOS Mainnet channel or start a new one?

Aaron Cox (jesta) — Greymass, [05.05.20 13:54]
The block_log is independent of this conversation, there's no derived state within it. All transactions will always be in the block_log, the various solutions just have different methods of extracting and generating the derived state from it. 

 From my point of view there's no much value at the moment getting those parties together. V1 history (native) is different than V2 (Hyperion) in far too many ways and will never be identical, and Chronicles from Amsterdam isn't even an API just a tool to help build datasets for APIs. Each wallet and app independently is going to choose which route they go based on their needs. 

 I'm willing to engage on the topic, but I don't see what we'd aim to accomplish.

**Comment by ericbutz** [comment]
We decided that we would look into creating a new get action call for integrators that will filter out duplicate trnsfiopubky calls.

**Comment by adsorptionenthalpy** [comment]
Eric Butz, [06.05.20 11:38]
@any_x, thanks for the info on this. Very helpful. There is still some concern that we have a history node that will return duplicate transactions for our wallet and exchange partners. So we somehow have to tell them how to manually filter FIO transfer transactions. @pawmmm suggested we create a modified get actions call that automatically does the filtering. Any thoughts on that approach?

anyx — TeamGreymass, [13.05.20 15:06]
[In reply to Eric Butz]
I still highly recommend against it. The format of the contract and its token action structure is identical to all EOSIO chains, so if they see this issue for FIO they are going to see it for EOS Mainnet and everything else. If its a multi-chain wallet (which most are), it seems to me that it is better to identify this commonality and solve it wallet-side. Helping the wallet understand this (as it relates to all EOSIO chains) would be nice of course.

We could likely identify an API-side improvement, but I would argue this is something that should be considered for a V2 spec history. V1 spec history is very blunt and returns a lot of not-so-useful data, it's not great. So, personally, I would suggest not departing further from EOSIO here and having wallets implement different strategies per-eosio chain, and instead help us with V2 spec. ;)

**Comment by ericbutz** [comment]
anyx — TeamGreymass, [13.05.20 15:06]
[In reply to Eric Butz]
I still highly recommend against it. The format of the contract and its token action structure is identical to all EOSIO chains, so if they see this issue for FIO they are going to see it for EOS Mainnet and everything else. If its a multi-chain wallet (which most are), it seems to me that it is better to identify this commonality and solve it wallet-side. Helping the wallet understand this (as it relates to all EOSIO chains) would be nice of course.

We could likely identify an API-side improvement, but I would argue this is something that should be considered for a V2 spec history. V1 spec history is very blunt and returns a lot of not-so-useful data, it's not great. So, personally, I would suggest not departing further from EOSIO here and having wallets implement different strategies per-eosio chain, and instead help us with V2 spec. ;)

**Comment by ericbutz** [comment]
Duplicate transaction issue was fixed with https://github.com/fioprotocol/fio/releases/tag/v2.0.0
Closing.
