### ISSUE TITLE
setabi corrupted the ABI

### ISSUE THREAD

**Issue by cc32d9** [fioprotocol/fio#215]
while applying this change:  https://github.com/fioprotocol/fio/pull/78/files

we detected that after "set abi",   "get abi" shows an incomplete ABI: some tables are missing. Also "set abi" with the previous version of ABI does not solve the problem, and it remains broken.

clio/cleos is only parsing JSIN, packing it into a binary form, and sending "eosio::setabi" action. Nothing seems to be broken in clio.

the system contract's setabi is quite identical to B1's original contract, with the only difference in name checking.

nodeos seems to be storing the ABI data as required. But probably some other memory corruption is cutting the ABI bytes.

Table names are going last in the serialized ABI bytes, so it seems like we see a truncated vector of bytes when we execute "get abi".

**Comment by cc32d9** [comment]
ABI serialized representation from abieos library:

```
struct abi_def {
    std::string version{};
    std::vector<type_def> types{};
    std::vector<struct_def> structs{};
    std::vector<action_def> actions{};
    std::vector<table_def> tables{};
    std::vector<clause_pair> ricardian_clauses{};
    std::vector<error_message> error_messages{};
    abi_extensions_type abi_extensions{};
    might_not_exist<std::vector<variant_def>> variants{};
};
```

so if tables are truncated, we see missing ones

**Comment by dapixcasey** [comment]
This issue was the result of binding the correct contract to the wrong contract account (eosio). Closing the issue.

**Comment by edrotthoff** [comment]
this was a none-issue. it is important to note that fio has many important accounts, and each important fio account owns a contract. Eosio account owns the fio.system contract and abi, then fio.token fio.address fio.treasury fio.reqobt fio.tpid and fio.fee each own the contract and abi of the same namesake. This was an error in calling set abi, the eosio account was assigned the fio.address abi, which will cause a fluster for sure...this issue is now closed.
