### ISSUE TITLE
Why does voteproducer require a FIO Address?

### ISSUE THREAD

**Issue by lukestokes** [fioprotocol/fio#47]
Other calls use the signing actor, a specified actor, or FIO public key. Is there a reason this call is different? It creates a workflow problem where someone may have a FIO account with tokens and they want to participate in governance and vote with those tokens, but they don't intend to use that account for FIO protocol activities.

**Comment by pawmmm** [comment]
The first version of vote did not require a FIO Address. We added it, because we wanted voting to be available without a fee (using bundled transaction), so that more users would vote. In that process, we picked an approach that's easiest to code and that was to always require FIO Address. We further felt, it would be a good thing to require a FIO Address to ensure all voters have hands-on experience with the protocol.

**Comment by aaroncox** [comment]
The justification of using bundled transactions makes sense - since I'm assuming an address is required to utilize those. However, the remaining justifications I respectfully disagree with, and believe using a FIO Address to vote should be an optional parameter or not included at all.

Counterpoints:

- You can have "hands-on experience" with the protocol and still want to vote using an account without an associated address. 
- Arguably this requirement is a barrier to voting, and does the opposite of encouraging some token holders to vote. This is because it requires additional steps (address registration/renewal) before allowing a specific token holder to vote. 
- Requiring duplicate data that could otherwise be derived as an input parameter of the transaction is potentially wasteful. The transaction already knows who the voter is based on the actor field, and the addition of the address creates no additional value beyond bundling (which could potentially use the actor input?). 
- The inclusion of a FIO address as an input parameter also creates a chain-specific implementation headaches for developers. We are experiencing this now, as our ESR signing protocol is designed to be chain-agnostic, and we will not be adding chain-specific templating values for things like FIO addresses. This means that transactions where the input includes a FIO address will not be compatible in a statically generated manner. 

If the goal is simply to make bundling available to avoid fees, I'd recommend a different approach to transactions. Forcing it as an input parameter at the base layer causes more of a downside than an upside in many respects.

**Comment by aaroncox** [comment]
> If bundled transactions are moved to the account actor then if someone buys an address and then sells it, that creates a problem as the remaining bundled transactions wouldn't travel along with the address to the new owner.

Is that actually a problem? I'll relay back to a DNS analogy, where if I buy a domain name and subsequently sell it, I wouldn't expect any "freebies" the registrar provided with my purchase to be transferred along with the domain registration transfer. Those were mine, as the original purchaser, and remain within my account on the registrars site. 

> the main driver for doing addresses with bundled tx was the driver to keep, as much as possible, the notion of the account away from the user

Considering they're already exposed to the notion of a public key and forced to use it, which essentially is the account itself, it could easily be presented in that fashion to avoid adding a new concept.

Regardless of how it's presented, one entity in the system (public key or account) owns a domain at a given moment in time. Users who manage addresses/domains need to know that it exists in some form because all native EOSIO objects are shared to this entity.

**Comment by pawmmm** [comment]
I think the right solution would be to make FIO Address optional (meaning it can be left blank) and if it is charge a fee. Thoughts?

**Comment by pawmmm** [comment]
I am recommending we make the following changes to resolve this issue:
* Allow fio_address on [voteproducer](https://developers.fioprotocol.io/api/api-spec/reference/vote-producer/vote-producer-model) and voteproxy(https://developers.fioprotocol.io/api/api-spec/reference/proxy-vote/proxy-vote-model) to be blank and if it is charge the fee instead of decrementing the bundled transaction

@lukestokes @aaroncox, let me know if you agree and I'll write up a FIP

**Comment by lukestokes** [comment]
@pawmmm works for me.

**Comment by pawmmm** [comment]
Now a FIP: https://github.com/fioprotocol/fips/blob/master/fip-9.md

Please review and provide feedback.

**Comment by aaroncox** [comment]
FIP-9 look and the making of the parameter options works for me as well 👍

**Comment by pawmmm** [comment]
Closing as FIP-9 has been accepted and will be developed.
